### ISSUE TITLE
Tesla-Config-Node does not store credetials correctly

### ISSUE THREAD

**Issue by LudwigWen** [onokje/node-red-contrib-tesla#1]
I started with your example. Created a new TeslaConfig-Node, filled all 3 data.
Flow shows "no missing configNode". But during run email&password are indefined  in 
file tesla.js 
function TeslaConfigNode(node) 
When i hardcode my data erverything works fine

**Comment by onokje** [comment]
I cannot reproduce your problem. But to explain the example a bit: I have an example config node in the example flow with a fake vehicle id. Just change the config to your email and password, and remove the vehicle ID. Save and deploy, and ignore the warning. Now you can send the "vehicles" command to find out what what your vehicle id is. Enter it in the config node, save and deploy.
You can also just remove the example config node and start from there.

**Comment by LudwigWen** [comment]
sorry was a problem between chair and screen.
Thanks for your help.
