### ISSUE TITLE
Tesla Authentication has changed

### ISSUE THREAD

**Issue by Walz83** [onokje/node-red-contrib-tesla#10]
Sadly node-red-contrib-tesla is not working anymore because authentication has changed

https://tesla-api.timdorr.com/api-basics/authentication

Can you pls fix it?
Thank you

**Comment by ChutneyMary** [comment]
Upvote...please, please, please.

**Comment by steveh80** [comment]
upvote!

**Comment by onokje** [comment]
Yep, will fix. I may be a few days, feel free to submit a pr if you want it faster ;)

**Comment by lassenygard** [comment]
The same issue with fixes is found here:
[https://github.com/timdorr/tesla-api/discussions/263](https://github.com/timdorr/tesla-api/discussions/263)

**Comment by onokje** [comment]
I have to wait until the teslajs package has been updated, since this library is based on that one. They are working on it
(for reference: https://github.com/mseminatore/TeslaJS/pull/209)

**Comment by onokje** [comment]
Fixed, at least partially. It works again if you don't use MFA. If you do use MFA, you need to wait a bit more, because it requires some additional work. 
Update to 1.0.3 (it may take a while for the new version to show up in node red)

**Comment by ChutneyMary** [comment]
I tried v1.0.3. Unfortunately without success. I don't have MFA enabled.

Perhaps coincidently, the Tesla phone app was then locked out. I get a 'Sign-In Failed - UNKNOWN_OWNERAPI_ERROR. txid: 99xxxxx-xxxx-xxx-xxxx-xxxxxxxxxxxxxxx. Please try again later.'

The timing of how it happened seemed to suggest that something had ruffled the Tesla servers and locked my account...

**Comment by Walz83** [comment]
Thank you very much. Works like a charm. 

I didn't have the errors described by ChutneyMary.

**Comment by Walz83** [comment]
Thank you very much. Works like a charm. 

I didn't have the errors described by ChutneyMary.
