### ISSUE TITLE
setChargeLimit help

### ISSUE THREAD

**Issue by bobneubaum-personal** [onokje/node-red-contrib-tesla#11]
First off, this is awesome, thank you for making this available!!!

I am trying to pass in a variable for this function.. where should I be passing "80" for instance?

**Comment by onokje** [comment]
In the message you pass to the tesla api node, set the `commandArgs` property on the msg object, and set it to an object containing the arguments you need. In the case of SetChargeLimit, this argument is called `amt`. 
So: msg.commandArgs = {amt: 80}. 

Easiest way to do this is to use a 'change' node and Set msg.commandArgs.amt to 80.

**Comment by bobneubaum-personal** [comment]
Perfect!  Thank you!  Attaching a screen shot of what I did exactly

![Screen Shot 2021-02-17 at 4 23 28 PM](https://user-images.githubusercontent.com/26330840/108269817-8a779000-713c-11eb-8f7e-ad821cd4e837.png)
