### ISSUE TITLE
Error deploying flow: credential type 'tesla-config' is not registered.

### ISSUE THREAD

**Issue by TomNijsen** [onokje/node-red-contrib-tesla#3]
I cannot deploy the example flow with my own credentials configured in the api node. Always getting an error: "Credential type 'tesla-config' is not registered" when trying to deploy my flow. If I then reopen the tesla-api node, my credentials are blank. Tried to re-insert and redeploy a dozen of times...
I also get a warning next to deploy option:
"Flows stopped due to missing node types.
tesla-config
tesla-api"

Thanks in advance for your response and support on this!

**Comment by TomNijsen** [comment]
I also can't find the 'tesla-config' node in my nodes list on the left of NodeRed dashboard, should it be in the list after the install? I use 'Manage palette' to install the node-red-contrib-tesla.

**Comment by samosss** [comment]
> I also can't find the 'tesla-config' node 

The Tesla Config Node is near the top right?

Underneath 'Deploy' button, in the next little panel, you should see a 'gear' icon, then scroll down to the Tesla config node (its usually grey backgrounded). In fact all configuration nodes are in here. What does that part show?
