### ISSUE TITLE
Car will not wakeup

### ISSUE THREAD

**Issue by kristianolofsson** [onokje/node-red-contrib-tesla#36]
Im trying this with a Tesla MY but can't get I to work, keep getting 408 and the car will not wakeup.
Tried both the wakeup command and during eg. unlock charging port to set the wakeup automatically.
The auth seems to work since the car shows up in list of vehicles.

**Comment by onokje** [comment]
The car may just have a bad connection. It is not really something this library can help you with, sorry. Just keep trying.

**Comment by osvedman** [comment]
Sorry to reopen this, but I'm definitely seeing a lot of 408 errors from this library, while if I open the Tesla app on my phone, it can connect just fine. What could be the reason for this? A 408 is a Timeout, so could it be that the library times out before the car responds, while the Tesla app has a bigger timeout window set?

**Comment by onokje** [comment]
I am actually seeing a lot of 408 errors myself lately. But I am also seeing it in the app. Perhaps Tesla changed or broke something. The library does not timeout, the response code is directly from the Tesla API. There is not really something I can do about it.

**Comment by osvedman** [comment]
Alright, thank you for the reply!

fre. 1. jul. 2022, 14:50 skrev Martin Schimmel ***@***.***>:
