### ISSUE TITLE
404 Response to 'wake'

### ISSUE THREAD

**Issue by delboy711** [onokje/node-red-contrib-tesla#42]
After working perfectly for months, in the last few days I have been getting "Error response: 404" to 'wake' commands.
'vehicle list' still works.

I assume this is because of a Tesla API change?

**Comment by onokje** [comment]
I have the same issues. I am still figuring out what's going on.

**Comment by Michael-K-at-GitHub** [comment]
Easiest way:
1 Redeploy all nodes
2 Open faulty tesla node in editor
3 Reselect your vehicle and click done
4 repeat step 2 und 3 for every other tesla node in your flows
5 Redeploy all nodes

**Comment by delboy711** [comment]
Yes That was it.  
Thanks

**Comment by onokje** [comment]
Nice1 guys.
