### ISSUE TITLE
[Question] What commands do not wakeup and what ones do?

### ISSUE THREAD

**Issue by SergioRius** [onokje/node-red-contrib-tesla#6]
I would like to know what commands can be issued without waking up the car.
I need to gather info about the car but don't want to wake it.

Also... is it possible to send a "sleep" command?

**Comment by onokje** [comment]
Only 'vehicle' and 'vehicles' do NOT wake up the car. All other commands are going to the car directly so it needs to be awake.
As far as I know there is no sleep command in the tesla API, if only that were true! It is my biggest feature request for the Tesla API :P

**Comment by SergioRius** [comment]
Gotcha! Thanks!
BTW find not right that if the car is "sleeping" and you send for example a "vehicleConfig" command, the return is an error, but the car wakes. More correct would be not waking the car or not throwing the error.

It's a pity that we cant send a "remote push" of the turnoff button in car -> service menu.
