### ISSUE TITLE
Error: getaddrinfo "EAI_AGAIN" owner-api.teslamotors.com

### ISSUE THREAD

**Issue by SergioRius** [onokje/node-red-contrib-tesla#9]
Now sending a wakeUp command with car in deep sleep results in a `Error: getaddrinfo "EAI_AGAIN" owner-api.teslamotors.com`

Is there a way of controlling this error so I can retry the request?
What should I look for in the wakeUp node output?

**Comment by onokje** [comment]
You can use a 'catch node' from node-red to catch errors. I'll see i can improve the error handling in the mean time.

**Comment by onokje** [comment]
Improved in 2.0.0 update
